---
---
---

# About the Landscape Ecohydrology Group at UVA

## What do we do?

Text text text

-   interdisciplinary work at the intersection of hydrology and biogeochemistry

-   broadly focused on how water quantity and quality is modified at different spatial (local site to watershed to continental) and temporal (sub-daily to decadal) scales. This work has the goal of helping stakeholders and communities address water issues, and develop understanding and/or tools to help them manage their water resources.

## Who are we?

I envision our group to be a vibrant group of researchers from diverse backgrounds (both in life and previous academic training) working together to understand the causes and towards solutions to complex socio-environmental phenomena. We use a variety of tools to tackle these problems - we use primarily computational techniques from data synthesis, numerical modeling, remote sensing, and machine learning. We work at the intersection of many fields and our combined expertise comes from areas such as environmental engineering, biogeochemistry, ecohydrology, geography, economics, and more!

### A bit about me {.unnumbered}

I

### Group Members {.unnumbered}

XXXX

For current members and alumni, check out our website!

### Our Values {.unnumbered}
