# Getting Started in Our Research Group

We're so thrilled that you've decided to join us at our research group at UVA! In this section, we'll outline some useful tips/steps that will help you get situated within our group specifically. Note that you should keep an eye out on instructions from the Department and UVA!

## 6 to 3 Months Before Arriving at UVA

+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Task                                                         | Resources/Notes                                                                                                                                                                   |
+==============================================================+===================================================================================================================================================================================+
| -   Start looking into housing options for the upcoming term | -   UVA Off Grounds Housing [Page](https://offgroundshousing.student.virginia.edu/): a decent place to look at listings                                                           |
|                                                              | -   More aggregated [resources](https://www.law.virginia.edu/charlottesville/housing)                                                                                             |
+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Confirm logistics for moving to UVA                      | -   We have some resources to defray *a portion* of the moving costs for non-local students at the lab. Please check with Fred to see what is available and get things in writing |
+--------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## 3 Months to Arrival at UVA

+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Task                                                                                                                                             | Resources/Notes                                                                                                                                                             |
+==================================================================================================================================================+=============================================================================================================================================================================+
| -   Early June: Ensure you have UVA account and email                                                                                            |                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Early June: Familiarize yourself with degree requirements and roughly plan out courses                                                       | -   UVA Registrar's [Catalog](http://records.ureg.virginia.edu/preview_program.php?catoid=55&poid=7276)                                                                     |
|                                                                                                                                                  |                                                                                                                                                                             |
|                                                                                                                                                  | -   Department [Requirements](https://evsc.as.virginia.edu/sites/evsc.as.virginia.edu/files/requirements_phd_1-2018.pdf) (expands on Registrar's Catalog)                   |
|                                                                                                                                                  |                                                                                                                                                                             |
|                                                                                                                                                  | -   [Upcoming courses](https://evsc.as.virginia.edu/schedule-upcoming-courses) in department                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Early June: Familiarize yourself with the EVSC Graduate Student Association and their graduate handbook                                      | -   Their main [page](https://evsc.as.virginia.edu/graduate-student-association)                                                                                            |
|                                                                                                                                                  |                                                                                                                                                                             |
|                                                                                                                                                  | -   Their handbook has helpful tips and resources made by, and for, grad students in our department. Handbook linked in GSA page above.                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   \~ Jul 1:Course Selection for Fall for New Graduate Students                                                                                 |                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Mid-July: Confirm whether you are enrolling in UVA health insurance or waive with proof of comparable coverage (have to do this every year!) | -   Students are required to be covered by some health insurance                                                                                                            |
|                                                                                                                                                  |                                                                                                                                                                             |
|                                                                                                                                                  | -   Details of UVA plan [here](https://www.studenthealth.virginia.edu/insurance); note that grad students on GRA or GTA in the academic year get a health insurance subsidy |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Explore student services + support at UVA and in the Department                                                                              | -   Student health and wellness: [link](https://www.studenthealth.virginia.edu/)                                                                                            |
|                                                                                                                                                  |                                                                                                                                                                             |
|                                                                                                                                                  | -   PhD Plus: [link](https://phdplus.virginia.edu/)                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Explore events, activities, services offered by UVA and Charlottesville                                                                      | -   a good start [here](https://gradstudies.virginia.edu/uva-and-charlottesville-guide)                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Prior to starting: Go over lab documentation (Sections 1 through 6 of this document)                                                         |                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   Early Aug: Complete Step 1 of the Department's Mentorship Agreement                                                                          | -   Please use the copy here (I've added a couple questions to help guide our discussion)                                                                                   |
|                                                                                                                                                  |                                                                                                                                                                             |
|                                                                                                                                                  | -   Do your best to fill it out but we will use it during our first meeting when you arrive!                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## First Week of the Term

+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Task                                                                  | Resources/Notes                                                                                |
+=======================================================================+================================================================================================+
| -   Get situated in your office and our lab (get ID card, keys, etc.) | -   See section in EVSC GSA handbook                                                           |
|                                                                       |                                                                                                |
|                                                                       | -   Key form located on left sidebar [here](https://evsc.as.virginia.edu/administrative-forms) |
+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| -   Set up personal lab computer + associated software                |                                                                                                |
|                                                                       |                                                                                                |
|     -   Research Group Slack                                          |                                                                                                |
|                                                                       |                                                                                                |
|     -   Research Group Calendar                                       |                                                                                                |
+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| -   Mid to Late August: Fall Term Begins                              | -   Enjoy!!                                                                                    |
+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| -   Set up meeting with Fred for check-in                             | -   Discuss mentorship agreement, schedule, plan for semester                                  |
+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------+

## First Term

+--------------------------------------------------------------------------------------------------------+-----------------+
| Task                                                                                                   | Resources/Notes |
+========================================================================================================+=================+
| -   Work towards finding the necessary habits and schedule for you to have a healthy work-life balance |                 |
+--------------------------------------------------------------------------------------------------------+-----------------+
|                                                                                                        |                 |
+--------------------------------------------------------------------------------------------------------+-----------------+
| -   \~Last week of fall term: Set up check-in meeting with Fred                                        |                 |
+--------------------------------------------------------------------------------------------------------+-----------------+
