# Team Management

There's a lot happening as you start your graduate degree. To make things easier for everyone, I will (force) the research group to use the following tools:

1.  Microsoft Outlook for the calendar functionality\*

2.  Slack for project and general intralab communications (as opposed to email)

3.  Github for version control and code storage

    \*you're free to use any other mail/calendar app! My one request is that you find one that can sync with my Outlook calendar so you can see my availability for meetings

I will highly recommend the following tools for ease of consistency (and general bad experiences with competing products), but you are more than welcome to use an alternative.

1.  Microsoft Word for manuscript writing
2.  Zotero for reference management (we have a lab account; integrates with Word or Google Docs)
3.  GitProject for project management
4.  OneDrive AND Group Sharepoint AND local/external hard drives for data backup

## Managing Up

To help me help you, it would be great for you to do the following:

-   Be prepared for our regular one-on-one meetings to: remind what was outstanding last time, discuss progress, new questions/roadblocks, and plans for next meeting. If you'd like a template to start with/adapt, consider using this

-   As a rule of thumb, if you're stuck on something for more than several hours, seek help!

-   Keeping good documentation of code, data, assumptions. I encourage you to use a combination of a markdown system (RMarkdown, Quarto, Jupyter notebook, etc.) for code and research notebook (e.g. OneNote)

-   I am happy to communicate via Slack messages and face-to-face chats

    -   Slack has the benefit of keeping a record of our discussion for posterity, and is great for short/easy questions

    -   Face-to-face is better for in-depth discussions, multiple topics, etc.

-   Keep on top of important dates for degree milestones/forms, conferences, etc. especially if you need feedback/signatures, etc. and tell Fred in advance!
